# PROJECT - 1 "CLASSIFICATION"

CLASSIFICATION is a technique where the data will be categorized into a given number of classes. The main goal of a classification problem is to identify the category/class to which a new data will fall under

PROJECT DESCRIPTION AND AGENDA
----------------------------------------------
Mushroom hunting (otherwise known as "Shrooming") is enjoying new peaks in popularity. The concept behind this handpick is simple and straight forward which helps us to learn which features of a particular mushroom spell certain death and which are most palatable in this dataset of mushroom characteristics. 
                                                                                        Talking about the dataset, this dataset includes recordings of hypothetical samples corresponding to 23 species of gilled mushrooms in the regions of Agaricus and Lepiota Family Mushroom drawn from The Audubon Society Field Guide to North American Mushrooms (1981). Each species is identified as definitely edible, definitely poisonous, or of unknown edibility and not recommended. This latter class was combined with the poisonous one. The Guide clearly states that there is no simple rule for determining the edibility of a mushroom
                                                                                        
THE AGENDA OF THIS PROJECT IS:

*To identify what types of machine learning models perform best on this dataset?

*Which features are most indicative of a poisonous mushroom?

>ATTRIBUTE INFORMATION:

1. cap-shape: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s
2. cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3. cap-color: brown=n,buff=b,cinnamon=c,gray=g,green=r, pink=p,purple=u,red=e,white=w,yellow=y
4. bruises?: bruises=t,no=f
5. odor: almond=a,anise=l,creosote=c,fishy=y,foul=f, musty=m,none=n,pungent=p,spicy=s
6. gill-attachment: attached=a,descending=d,free=f,notched=n
7. gill-spacing: close=c,crowded=w,distant=d
8. gill-size: broad=b,narrow=n
9. gill-color: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e,white=w,yellow=y
10. stalk-shape: enlarging=e,tapering=t
11. stalk-root: bulbous=b,club=c,cup=u,equal=e, rhizomorphs=z,rooted=r,missing=?
12. stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s
13. stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s
14. stalk-color-above-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
15. stalk-color-below-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
16. veil-type: partial=p,universal=u
17. veil-color: brown=n,orange=o,white=w,yellow=y
18. ring-number: none=n,one=o,two=t
19. ring-type: cobwebby=c,evanescent=e,flaring=f,large=l, none=n,pendant=p,sheathing=s,zone=z
20. spore-print-color: black=k,brown=n,buff=b,chocolate=h,green=r, orange=o,purple=u,white=w,yellow=y
21. population: abundant=a,clustered=c,numerous=n, scattered=s,several=v,solitary=y
22. habitat: grasses=g,leaves=l,meadows=m,paths=p, urban=u,waste=w,woods=d

>DATA PRE PROCESSING

In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import scatter_matrix
%matplotlib inline
%matplotlib notebook

#For model evaluation and development
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')

In [59]:
df = pd.read_csv("mushrooms.csv")
df.head()

class cap-shape cap-surface  ... spore-print-color population habitat
0     p         x           s  ...                 k          s       u
1     e         x           s  ...                 n          n       g
2     e         b           s  ...                 n          n       m
3     p         x           y  ...                 k          s       u
4     e         x           s  ...                 n          a       g

[5 rows x 23 columns]

In [60]:
df.shape

(8124, 23)

In [61]:
df['class'].value_counts()

e    4208
p    3916
Name: class, dtype: int64

In [ ]:
df.describe()

class cap-shape cap-surface  ... spore-print-color population habitat
count   8124      8124        8124  ...              8100       8124    8124
unique     2         6           4  ...                 9          6       7
top        e         x           y  ...                 w          v       d
freq    4208      3656        3244  ...              2388       4040    3148

[4 rows x 23 columns]

EDA (Exploratory Data Visualization)
-------------------------------------------

>CHECK FOR NULL VALUES

The very immediate step after loading the data would be checking for any missing values that are present in the data. Missing data can reduce the statistical power of a study and can produce biased estimates, leading to invalid conclusions. Hence, it is important to remove any missing values that are present in the dataset

In [62]:
for col in df.columns:
    print("{} : {}".format(col, df[col].isnull().sum()))

class : 0
cap-shape : 0
cap-surface : 0
cap-color : 0
bruises : 27
odor : 0
gill-attachment : 0
gill-spacing : 12
gill-size : 19
gill-color : 28
stalk-shape : 0
stalk-root : 0
stalk-surface-above-ring : 0
stalk-surface-below-ring : 20
stalk-color-above-ring : 21
stalk-color-below-ring : 0
veil-type : 0
veil-color : 18
ring-number : 0
ring-type : 0
spore-print-color : 24
population : 0
habitat : 0


As we see, there are missing values present in 8 columns in the dataset. Missing data can be handled in multiple ways: 
1. By imputing the values with simple average or median
2. Replace by most frequent value
3. By simply droping the rows that comtain the missing values.
The type of handling method depends mainly on type of data, as it is not appropriate to perform statistical calculations on categorical data. Besides, due to the presence of sufficient amount of data and by considering the type of data that we have, in this project we are going to drop the rowns that contains those missing values.

In [63]:
df.dropna(inplace=True)
df.shape

(7967, 23)

In [64]:
df['class'].value_counts()

e    4075
p    3892
Name: class, dtype: int64

In [65]:
#Checking for Imbalance in the Dataset

sns.countplot(df['class'])

<IPython.core.display.Javascript object>

Looking at the graph, it is clear that the dataset is very much balanced!

In [66]:
def plot_data(hue, data):
    for i, col in enumerate(data.columns):
        plt.figure(i)
        sns.set(rc={'figure.figsize':(12,9)})
        ax = sns.countplot(x=data[col], hue=hue, data=data) 

In [67]:
hue = df[ 'class' ] 
data_for_plot = df.drop( 'class' , 1) 
plot_data(hue, data_for_plot) 

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [68]:
X = df.loc[:, df.columns != 'class']
X.head()

cap-shape cap-surface cap-color  ... spore-print-color population habitat
0         x           s         n  ...                 k          s       u
1         x           s         y  ...                 n          n       g
2         b           s         w  ...                 n          n       m
3         x           y         w  ...                 k          s       u
4         x           s         g  ...                 n          a       g

[5 rows x 22 columns]

In [69]:
y = df['class'].to_frame()
y.head()

class
0     p
1     e
2     e
3     p
4     e

Data Wrangling
------------------

It is not recommended to apply label encoding for those features that have values more than 2. The reason for this is to avoid giving more importance to the other values as the Label ecoding assigns values as 0,1,2,..

In order to handle this type of problems, we use One hot vectorization

In [70]:
X_enc = pd.get_dummies(X)
X_enc.head()

cap-shape_b  cap-shape_c  cap-shape_f  ...  habitat_p  habitat_u  habitat_w
0            0            0            0  ...          0          1          0
1            0            0            0  ...          0          0          0
2            1            0            0  ...          0          0          0
3            0            0            0  ...          0          1          0
4            0            0            0  ...          0          0          0

[5 rows x 117 columns]

In [71]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_std = scaler.fit_transform(X_enc)


In [72]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_enc = le.fit_transform(y.values.ravel())

y_enc

array([1, 0, 0, ..., 0, 1, 0])

Model Building
------------------
Since, classification comes under supervised learning, it is important to divide the data into Training and Testing data sets before building any model.

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_std,y_enc,train_size=0.75,test_size=0.25,random_state=4)

In [74]:
X_train.shape

(5975, 117)

In [75]:
y_train.shape

(5975,)

ENSEMBLING
-----------------
>HARD VOTING

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import VotingClassifier

log_clf = LogisticRegression()
log_clf.fit(X_train, y_train)
knn_clf = KNeighborsClassifier(7)
knn_clf.fit(X_train, y_train)


voting_clf = VotingClassifier(estimators=[('lr', log_clf), ('knn', knn_clf)], voting='hard')
voting_clf.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
for clf in (log_clf, knn_clf, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 1.0
KNeighborsClassifier 1.0
VotingClassifier 1.0


>SOFT VOTING

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import VotingClassifier

log_clf = LogisticRegression()
log_clf.fit(X_train, y_train)
knn_clf = KNeighborsClassifier(7)
knn_clf.fit(X_train, y_train)


voting_clf = VotingClassifier(estimators=[('lr', log_clf), ('knn', knn_clf)], voting='soft')
voting_clf.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
for clf in (log_clf, knn_clf, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 1.0
KNeighborsClassifier 1.0
VotingClassifier 1.0


BAGGING & PASTING
------------------

>1. MODEL 1 - DECISION TREE CLASSIFIER
--------------------------------------
>FINDING BEST PARAMETERS FOR BAGGING CLASSIFIER USING GRID SEARCH

In [ ]:
param_grid = {'n_estimators': [50,100,200,500],
              'max_samples': [50,100,200,400]}

grid_search = GridSearchCV(BaggingClassifier(random_state = 0), param_grid, cv=5, return_train_score=True, n_jobs= -1)
grid_search.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Best parameters: {'max_samples': 400, 'n_estimators': 200}
Best cross-validation score: 1.00


>FINDING BEST PARAMETERS FOR DECISION TREE

In [ ]:
param_grid = {'max_depth': np.arange(1, 10)}
grid_search = GridSearchCV(DecisionTreeClassifier(random_state=0), param_grid, cv=5, return_train_score=True, n_jobs= -1)
grid_search.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Best parameters: {'max_depth': 7}
Best cross-validation score: 1.00


##### Rebuilding the model with best parameters

In [ ]:
dt_clf = DecisionTreeClassifier(max_depth = 8, random_state=0)
bag_clf = BaggingClassifier(dt_clf, n_estimators=500, max_samples=400, bootstrap=True, n_jobs=-1, random_state=0)

bag_clf.fit(X_train, y_train)
y_pred = bag_clf.predict(X_test)

print('Score after Bagging on Decision Tree Classifier on Train Set: {:.2f}'.format(bag_clf.score(X_train, y_train)))
print('Score after Bagging on Decision Tree Classifier on Test Set: {:.2f}'.format(bag_clf.score(X_test, y_test)))

Score after Bagging on Decision Tree Classifier on Train Set: 1.00
Score after Bagging on Decision Tree Classifier on Test Set: 1.00


###### Accuracy of the Model - Bagging classifier with Decision Tree Classifier

In [ ]:
print("Accuracy of the Classifier : ", accuracy_score(y_test, y_pred).round(4))

Accuracy of the Classifier :  0.998


##### Confusion Matrix

In [ ]:
pred_test = bag_clf.predict(X_test)
pred_train = bag_clf.predict(X_train)
confusion_test = confusion_matrix(y_test, pred_test)
confusion_train = confusion_matrix(y_train, pred_train)
print("Confusion matrix for test:\n{}".format(confusion_test))
print("Confusion matrix for train:\n{}".format(confusion_train))

Confusion matrix for test:
[[1034    0]
 [   4  954]]
Confusion matrix for train:
[[3041    0]
 [  12 2922]]


##### Classification report for the model 

In [ ]:
print(classification_report(y_test, pred_test, target_names=["Defaulter 0", "Non Defaulter 1"]))

                 precision    recall  f1-score   support

    Defaulter 0       1.00      1.00      1.00      1034
Non Defaulter 1       1.00      1.00      1.00       958

       accuracy                           1.00      1992
      macro avg       1.00      1.00      1.00      1992
   weighted avg       1.00      1.00      1.00      1992



### Model 2 - Random Forest

#### Finding best parameter for Random Forest Classifier

In [ ]:
param_grid = {'n_estimators': [50,100,200,500],
              'max_depth': np.arange(1, 10)}

grid_search = GridSearchCV(RandomForestClassifier(random_state=0), param_grid, cv=5, return_train_score=True, n_jobs= -1)
grid_search.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Best parameters: {'max_depth': 7, 'n_estimators': 100}
Best cross-validation score: 1.00


##### RandomForest Classifier model with the best parameters




In [ ]:
rnd_clf = RandomForestClassifier(n_estimators=50, max_depth = 9, bootstrap=True, n_jobs=-1, random_state=0)
rnd_clf.fit(X_train, y_train)

y_pred_rf = rnd_clf.predict(X_test)

print('Score after Bagging on Decision Tree Classifier on Train Set: {:.2f}'.format(rnd_clf.score(X_train, y_train)))
print('Score after Bagging on Decision Tree Classifier on Test Set: {:.2f}'.format(rnd_clf.score(X_test, y_test)))

Score after Bagging on Decision Tree Classifier on Train Set: 1.00
Score after Bagging on Decision Tree Classifier on Test Set: 1.00


#### Accuracy of the Model

In [ ]:
print("Accuracy of the Classifier : ", accuracy_score(y_test, y_pred).round(4))

Accuracy of the Classifier :  0.998


CONFUSION MATRIX

In [ ]:
pred_test = rnd_clf.predict(X_test)
pred_train = rnd_clf.predict(X_train)
confusion_test = confusion_matrix(y_test, pred_test)
confusion_train = confusion_matrix(y_train, pred_train)
print("Confusion matrix for test:\n{}".format(confusion_test))
print("Confusion matrix for train:\n{}".format(confusion_train))

Confusion matrix for test:
[[1034    0]
 [   0  958]]
Confusion matrix for train:
[[3041    0]
 [   0 2934]]


CLASSFICATION REPORT

In [ ]:
print(classification_report(y_test, pred_test, target_names=["Defaulter 0", "Non Defaulter 1"]))

                 precision    recall  f1-score   support

    Defaulter 0       1.00      1.00      1.00      1034
Non Defaulter 1       1.00      1.00      1.00       958

       accuracy                           1.00      1992
      macro avg       1.00      1.00      1.00      1992
   weighted avg       1.00      1.00      1.00      1992



## Pasting


### Model 1 - Decision Tree 

##### Finding best parameter for Bagging Classifier

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import BaggingClassifier
param_grid = {'n_estimators': [50,100,200,500],
              'max_samples': [50,100,200,400]}

grid_search = GridSearchCV(BaggingClassifier(random_state = 0), param_grid, cv=5, return_train_score=True)
grid_search.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Best parameters: {'max_samples': 400, 'n_estimators': 200}
Best cross-validation score: 1.00


##### Finding best parameter for Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'max_depth': np.arange(1, 10)}
grid_search = GridSearchCV(DecisionTreeClassifier(random_state=0), param_grid, cv=5, return_train_score=True, verbose=True, n_jobs= -1)
grid_search.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Fitting 5 folds for each of 9 candidates, totalling 45 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  14 out of  45 | elapsed:    0.2s remaining:    0.4s


Best parameters: {'max_depth': 7}
Best cross-validation score: 1.00


[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:    0.4s finished


#### Rebuilding the model with best parameters

In [ ]:
dt_clf = DecisionTreeClassifier(max_depth = 8, random_state=0)
past_clf = BaggingClassifier(dt_clf, n_estimators=500, max_samples=400, bootstrap=False, n_jobs=-1, random_state=0)

past_clf.fit(X_train, y_train)
y_pred = past_clf.predict(X_test)

print('Score after Bagging on Decision Tree Classifier on Train Set: {:.2f}'.format(past_clf.score(X_train, y_train)))
print('Score after Bagging on Decision Tree Classifier on Test Set: {:.2f}'.format(past_clf.score(X_test, y_test)))

Score after Bagging on Decision Tree Classifier on Train Set: 1.00
Score after Bagging on Decision Tree Classifier on Test Set: 1.00


#### Accuracy of the model

In [ ]:
print("Accuracy  of the model : ", accuracy_score(y_test, y_pred).round(4))

Accuracy  of the model :  0.998


#### Confusion Matrix

In [ ]:
pred_test = past_clf.predict(X_test)
pred_train = past_clf.predict(X_train)
confusion_test = confusion_matrix(y_test, pred_test)
confusion_train = confusion_matrix(y_train, pred_train)
print("Confusion matrix for test:\n{}".format(confusion_test))
print("Confusion matrix for train:\n{}".format(confusion_train))

Confusion matrix for test:
[[1034    0]
 [   4  954]]
Confusion matrix for train:
[[3041    0]
 [  12 2922]]


#### Classification Report

In [ ]:
print(classification_report(y_test, pred_test, target_names=["Defaulter 0", "Non Defaulter 1"]))

                 precision    recall  f1-score   support

    Defaulter 0       1.00      1.00      1.00      1034
Non Defaulter 1       1.00      1.00      1.00       958

       accuracy                           1.00      1992
      macro avg       1.00      1.00      1.00      1992
   weighted avg       1.00      1.00      1.00      1992



### Model 2 - Random Forest

#### Finding best parameter for Random forest classifier

In [ ]:
param_grid = {'n_estimators': [50,100,200,500],
              'max_depth': np.arange(1, 10)}

grid_search = GridSearchCV(RandomForestClassifier(random_state=0), param_grid, cv=5, return_train_score=True, verbose=True, n_jobs= -1)
grid_search.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Fitting 5 folds for each of 36 candidates, totalling 180 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done 180 out of 180 | elapsed:   15.5s finished


Best parameters: {'max_depth': 7, 'n_estimators': 100}
Best cross-validation score: 1.00


##### Building the RandomForest Classifier model with the best parameters

In [ ]:
rnd_clf = RandomForestClassifier(n_estimators=50, max_depth = 9, max_leaf_nodes=10, bootstrap=False, n_jobs=-1, random_state=0)
rnd_clf.fit(X_train, y_train)

y_pred_rf = rnd_clf.predict(X_test)

print('Score after Bagging on Decision Tree Classifier on Train Set: {:.2f}'.format(rnd_clf.score(X_train, y_train)))
print('Score after Bagging on Decision Tree Classifier on Test Set: {:.2f}'.format(rnd_clf.score(X_test, y_test)))

Score after Bagging on Decision Tree Classifier on Train Set: 0.99
Score after Bagging on Decision Tree Classifier on Test Set: 0.99


ACCURACY

In [ ]:
print("Accuracy of the model : ", accuracy_score(y_test, y_pred).round(4))

Accuracy of the model :  0.998


CONFUSION MATRIX

In [ ]:
pred_test = rnd_clf.predict(X_test)
pred_train = rnd_clf.predict(X_train)
confusion_test = confusion_matrix(y_test, pred_test)
confusion_train = confusion_matrix(y_train, pred_train)
print("Confusion matrix for test:\n{}".format(confusion_test))
print("Confusion matrix for train:\n{}".format(confusion_train))

Confusion matrix for test:
[[1034    0]
 [  18  940]]
Confusion matrix for train:
[[3041    0]
 [  70 2864]]


CLASSIFICATION REPORT

In [ ]:
print(classification_report(y_test, pred_test, target_names=["Defaulter 0", "Non Defaulter 1"]))

                 precision    recall  f1-score   support

    Defaulter 0       0.98      1.00      0.99      1034
Non Defaulter 1       1.00      0.98      0.99       958

       accuracy                           0.99      1992
      macro avg       0.99      0.99      0.99      1992
   weighted avg       0.99      0.99      0.99      1992



## AdaBoost Boosting

### Model 1 - Decision Tree Classifier (max_depth = 1) with AdaBoosting> Using the Parameters from Grid Search on LSVM

##### Finding best parameters for adaboost boosting for Decision Tree Classifier

In [ ]:
param_grid = {'n_estimators': [50,100,200,500],
              'learning_rate': [.01, .05, .1, 1]}

grid_search_ada = GridSearchCV(AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),random_state = 0), param_grid, cv=5, return_train_score=True, verbose=True, n_jobs=-1)
grid_search_ada.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search_ada.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search_ada.best_score_))

Fitting 5 folds for each of 16 candidates, totalling 80 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed:  2.8min finished


Best parameters: {'learning_rate': 0.1, 'n_estimators': 200}
Best cross-validation score: 1.00


###### Decision Tree with max_depth 1 on the dataset before adaboost boosting

In [ ]:
dt_clf = DecisionTreeClassifier(max_depth = 1, random_state=0)
dt_clf.fit(X_train, y_train)
y_pred = dt_clf.predict(X_test)

print("Accuracy of the decision tree classifier ", accuracy_score(y_test, y_pred).round(4))

Accuracy of the decision tree classifier  0.8956


###### Applying AdaBoost Boosting on the decision tree classifier with max_depth 1

In [ ]:
ada_clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1), n_estimators=500, algorithm="SAMME.R", learning_rate=1, random_state=0)
ada_clf.fit(X_train, y_train)
y_pred = ada_clf.predict(X_test)
from  sklearn.metrics import accuracy_score
print("Accuracy of the decision tree classifier after adaboost boosting",accuracy_score(y_test, y_pred).round(4))

Accuracy of the decision tree classifier after adaboost boosting 1.0


##### Observation - We can see that adaboost boosting has improved the accuracy of the decision tree classifer by approx 23%.

### Model 2 - Logistic Regression with AdaBoost

#### Grid search to find best parameters for Adaboost boosting for logistic regression 

In [ ]:
param_grid = {'n_estimators': [50,100,200,500],
              'learning_rate': [.01, .05, .1, 1]}

grid_search_logit = GridSearchCV(AdaBoostClassifier(LogisticRegression(),algorithm="SAMME.R",random_state = 0), param_grid, cv=5, return_train_score=True, verbose=True, n_jobs= -1)
grid_search_logit.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search_logit.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search_logit.best_score_))

Fitting 5 folds for each of 16 candidates, totalling 80 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed:  1.8min finished


Best parameters: {'learning_rate': 0.01, 'n_estimators': 500}
Best cross-validation score: 1.00


#### Applying logistic Regression on the data

In [ ]:
from sklearn.svm import LinearSVC
lreg = LinearSVC()
lreg.fit(X_train,y_train)
y_pred = lreg.predict(X_test)
from  sklearn.metrics import accuracy_score
print("Accuracy for logistic regression model :", accuracy_score(y_test, y_pred).round(4))

Accuracy for logistic regression model : 1.0


#### Observation : We can see that there is little change on the result of Logistic Regression after applying adaboost boosting on the dataset.

### Gradient Boosting

#### Finding best parameters for gradient boosting

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
param_grid = {'n_estimators': [50,100,200,500],
              'learning_rate': [.01, .05, .1, 1], 'max_depth': np.arange(1, 5)}

grid_search = GridSearchCV(GradientBoostingClassifier(random_state = 0), param_grid, cv=5, return_train_score=True, n_jobs=-1, verbose=True)
grid_search.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Fitting 5 folds for each of 64 candidates, totalling 320 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   57.0s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:  5.1min
[Parallel(n_jobs=-1)]: Done 320 out of 320 | elapsed:  6.5min finished


Best parameters: {'learning_rate': 0.01, 'max_depth': 4, 'n_estimators': 500}
Best cross-validation score: 1.00


#### Building the gradient boosting model with best parameters

In [77]:
gbrt = GradientBoostingClassifier(random_state=0, learning_rate=0.1, max_depth = 7, n_estimators=500)
gbrt.fit(X_train, y_train)
y_pred = gbrt.predict(X_test)

#### Accuracy of the Model

In [78]:
print("Accuracy of the model after gradient boosting",accuracy_score(y_test, y_pred).round(4))

Accuracy of the model after gradient boosting 1.0


CONFUSION MATRIX

In [79]:
pred_test = gbrt.predict(X_test)
pred_train = gbrt.predict(X_train)
confusion_test = confusion_matrix(y_test, pred_test)
confusion_train = confusion_matrix(y_train, pred_train)
print("Confusion matrix for test:\n{}".format(confusion_test))
print("Confusion matrix for train:\n{}".format(confusion_train))

Confusion matrix for test:
[[1034    0]
 [   0  958]]
Confusion matrix for train:
[[3041    0]
 [   0 2934]]


### PCA for Classification

In [80]:
from sklearn.decomposition import PCA
pca_classification = PCA(n_components = .98, random_state = 0)
X_train_class = pca_classification.fit_transform(X_train)
X_test_class = pca_classification.transform(X_test)

#### Number of components after PCA

In [81]:
pca_classification.n_components_

68

### 1. KNN Classifier with Principal Component

#### Finding best parameters for the model

In [82]:
param_grid = {'n_neighbors': range(1,10)}
grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, return_train_score=True, verbose = True)
grid_search.fit(X_train_class, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Fitting 5 folds for each of 9 candidates, totalling 45 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best parameters: {'n_neighbors': 1}
Best cross-validation score: 1.00


[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed:  1.5min finished


In [83]:
knn = KNeighborsClassifier(n_neighbors=8)
knn.fit(X_train_class, y_train)
print('Train score on best parameters {}'.format(knn.score(X_train_class,y_train)))
print('Test score on best parameters {}'.format(knn.score(X_test_class,y_test)))

Train score on best parameters 0.9994979079497908
Test score on best parameters 0.9994979919678715


### 2. Logistic Regression with Principal Component

#### Finding best parameters for the model

In [84]:
param_grid_svm = {'C': [0.001, 0.01, 0.1, 1, 10, 100], 'penalty':['l1','l2']}
grid_search = GridSearchCV(LogisticRegression(), param_grid_svm, cv=5, return_train_score=True)
grid_search.fit(X_train_class, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.6f}".format(grid_search.best_score_))

Best parameters: {'C': 10, 'penalty': 'l2'}
Best cross-validation score: 1.000000


#### Building the model with best parameters

In [85]:
lg = LogisticRegression(C=0.001,penalty='l2',solver='liblinear').fit(X_train_class, y_train)
print('Train score on best parameters for Logistic Regression model {:.3f}'.format(lg.score(X_train_class,y_train)))
print('Test score on best parameters for Logistic Regression model {:.3f}'.format(lg.score(X_test_class,y_test)))

Train score on best parameters for Logistic Regression model 0.996
Test score on best parameters for Logistic Regression model 0.996


#### Confusion Matrix

In [86]:
pred_logreg_test = lg.predict(X_test_class)
pred_logreg_train = lg.predict(X_train_class)
confusion_test = confusion_matrix(y_test, pred_logreg_test)
confusion_train = confusion_matrix(y_train, pred_logreg_train)
print("Confusion matrix for test:\n{}".format(confusion_test))
print("Confusion matrix for train:\n{}".format(confusion_train))

Confusion matrix for test:
[[1031    3]
 [   4  954]]
Confusion matrix for train:
[[3026   15]
 [   8 2926]]


#### Classification Report 

In [87]:
print(classification_report(y_test, pred_logreg_test, target_names=["Defaulter 0", "Non Defaulter 1"]))

                 precision    recall  f1-score   support

    Defaulter 0       1.00      1.00      1.00      1034
Non Defaulter 1       1.00      1.00      1.00       958

       accuracy                           1.00      1992
      macro avg       1.00      1.00      1.00      1992
   weighted avg       1.00      1.00      1.00      1992



### 3. Support Vector Machine Classifiers

#### Finding best parameters using gridsearch

In [88]:
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10],
              'gamma': [0.001, 0.01, 0.1, 1, 10], 'degree':[2,3,4]}

grid_search = GridSearchCV(SVC(), param_grid, cv=5, return_train_score=True, n_jobs = 1, verbose = True)
grid_search.fit(X_train_class, y_train)

print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))
print("Test set score: {:.2f}".format(grid_search.score(X_test_class, y_test)))

Fitting 5 folds for each of 75 candidates, totalling 375 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


KeyboardInterrupt: ignored

#### Building models for various kernels in SVC according to the best parameters obtained using gridsearch and then finding train and test score for each model

#### (a) Linear SVC

In [89]:
classifier1 = LinearSVC(C=0.001).fit(X_train_class, y_train)

#### Train and Test score for Linear SVC

In [91]:
print('Train score on best parameters for SVC kernel - Linear {}'.format(classifier1.score(X_train_class,y_train)))
print('Test score on best parameters for SVC kernel - Linear {}'.format(classifier1.score(X_test_class,y_test)))

Train score on best parameters for SVC kernel - Linear 0.9994979079497908
Test score on best parameters for SVC kernel - Linear 0.9994979919678715


#### (b) SVC kernel - Linear

In [92]:
classifier2 = SVC(kernel='linear', C=0.001).fit(X_train_class, y_train)

#### Train and Test score for SVC kernel - Linear

In [93]:
print('Train score on best parameters for SVC kernel - Linear {}'.format(classifier2.score(X_train_class,y_train)))
print('Test score on best parameters for SVC kernel - Linear {}'.format(classifier2.score(X_test_class,y_test)))

Train score on best parameters for SVC kernel - Linear 0.9994979079497908
Test score on best parameters for SVC kernel - Linear 0.9994979919678715


#### (c) SVC kernel - rbf

In [95]:
classifier3 = SVC(kernel='rbf', gamma=0.001, C=0.001).fit(X_train_class, y_train)

#### Train and Test score for SVC kernel - rbf

In [96]:
print('Train score on best parameters for SVC kernel - rbf {}'.format(classifier3.score(X_train_class,y_train)))
print('Test score on best parameters for SVC kernel - rbf {}'.format(classifier3.score(X_test_class,y_test)))

Train score on best parameters for SVC kernel - rbf 0.5089539748953975
Test score on best parameters for SVC kernel - rbf 0.5190763052208835


#### (d) SVC kernel - poly

In [97]:
classifier4 = SVC(kernel='poly', degree=1, C=0.001).fit(X_train_class, y_train)

#### Train and Test score for SVC kernel - poly

In [98]:
print('Train score on best parameters for SVC kernel - poly {}'.format(classifier4.score(X_train_class,y_train)))
print('Test score on best parameters for SVC kernel - poly {}'.format(classifier4.score(X_test_class,y_test)))

Train score on best parameters for SVC kernel - poly 0.7307112970711297
Test score on best parameters for SVC kernel - poly 0.7464859437751004


### 4. Decision Tree Classifier

#### Finding best parameters for the model using gridsearch

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid = {'max_depth': np.arange(1, 5)}
grid_search.fit(X_train_class, y_train)
grid_search = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5, return_train_score=True, n_jobs = -1, verbose = True)
grid_search.fit(X_train_class, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Fitting 5 folds for each of 75 candidates, totalling 375 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


#### Building the model using the best parameters obtained using gridsearch


In [100]:
dtree = DecisionTreeClassifier(max_depth=7, random_state=0)
dtree.fit(X_train_class, y_train)

print("Accuracy on training set: {:.6f}".format(dtree.score(X_train_class, y_train)))
print("Accuracy on test set: {:.6f}".format(dtree.score(X_test_class, y_test)))

Accuracy on training set: 1.000000
Accuracy on test set: 0.997992


## Comparing results obtained using PCA for all models with the results for models without PCA.

In [ ]:
outside = ['Before PCA','Before PCA','After PCA','After PCA']
inside = ['Training Accuracy','Test Accuracy','Training Accuracy','Test Accuracy']
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

#### Scores of models from Project 1

In [ ]:
data_class = np.array([(0.9928,0.6556,0.5103,0.7795,0.7893,0.7820,0.6233),
                     (0.8948,0.6484,0.5129,0.7895,0.7936,0.7910,0.6209),
                     (0.6658,0.5080,0.5078,0.5078,0.5078,0.5078,0.5976),
                     (0.5503,0.4930,0.4932,0.4932,0.4932,0.4932,0.5609)])

In [ ]:
df = pd.DataFrame(data_class,index=hier_index,columns=['KNN','Logistic','LinearSVC','SVC kernel - Linear','SVC kernel - rbf','SVC kernel - poly','Decision Tree'])

In [ ]:
import seaborn as sns

cm = sns.light_palette("#2ecc71", as_cmap=True)
s = df.style.background_gradient(cmap='PuBu')
s

##### CONCLUSION: In case of classification we can clearly see that there has been slight improvement in the test scores of most models after PCA as compared to the test scores before PCA. In case of decision tree we can see that the test scores or accuracy was better without PCA. But, according to most of the results obtained, PCA has been helpful since it has reduced the number of features hence reducing the computational power of the algorithms and moreover, it has also increased the accuracy of most of the models.

## Neural Networks - Classification

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

In [ ]:
def create_model():
    model = Sequential()
    model.add(Dense(1, input_dim = 117, activation='relu'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

##### Setting the seed 

In [ ]:
seed = 10
np.random.seed(10)

__Using GridSearch to find out best parmeters__

In [ ]:

model = KerasClassifier(build_fn = create_model, verbose = 0)

param_grid = {'batch_size':[10,20,30] , 'epochs':[50, 100]}
grid_search = GridSearchCV(estimator= model, param_grid = param_grid, cv = 5, n_jobs=2, verbose= True)

grid_search_result = grid_search.fit(X_train, y_train)
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Fitting 5 folds for each of 6 candidates, totalling 30 fits


[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  30 out of  30 | elapsed:  7.5min finished


Best parameters: {'batch_size': 10, 'epochs': 50}
Best cross-validation score: 0.99


#### Creating Model

In [ ]:
model = Sequential()
model.add(Dense(1, input_dim = 117, activation='relu'))


#### Compiling Model

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#### Fitting the Model

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=30)

#### Evaluating the Model and calculating the accuracy

In [ ]:
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

In [ ]:
y_predict = model.predict(X_test)
y_predict